# Use the official .NET 8 SDK to build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY ./YourProjectName/*.csproj ./YourProjectName/
RUN dotnet restore ./YourProjectName/YourProjectName.csproj

# Copy everything and build
COPY . .
WORKDIR /app/YourProjectName
RUN dotnet publish -c Release -o /out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .

# Expose port 
EXPOSE 5288

# Define entrypoint
ENTRYPOINT ["dotnet", "YourProjectName.dll"]
