# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy solution and project files
COPY *.sln .                                   
COPY ./server/FoodApplication/*.csproj ./FoodApplication/ 

# Move to project folder and restore
WORKDIR /app/FoodApplication
RUN dotnet restore

# Copy rest of the files
COPY ./server/FoodApplication .             
RUN dotnet publish -c Release -o /out

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .

EXPOSE 5288
ENTRYPOINT ["dotnet", "FoodApplication.dll"]
