# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy solution and project files
COPY FoodApplication.sln .
COPY FoodApplication/*.csproj ./FoodApplication/

# Restore dependencies
WORKDIR /app/FoodApplication
RUN dotnet restore

# Copy the rest of the source code
COPY FoodApplication/. .

# Publish app
RUN dotnet publish -c Release -o /out /p:UseAppHost=false

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out .

EXPOSE 5288
ENTRYPOINT ["dotnet", "FoodApplication.dll"]
